### ISSUE TITLE
0.9.1 is not compatible with HH stable branch O_O

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub-modules-mail#102]
When running HumHub in from the stable branch, update the mail module to v 0.9.1, visit a users profile. Throwing class constant not found exception. 

Recommendation: master branch should follow Humhub master. stable branch should be available via the HumHub marketplace in the application. `master` should be available only for those ready/willing/able to update to unstable code.
OR
`master` is your stable all the time branch with `devel` being the edge code base.

Either way, 0.9.1 is not usable with HH stable branch at this moment.

**Comment by buddha87** [comment]
Could you provide the full stack trace please?

**Comment by davidjeddy** [comment]
Here you go, got both the Exception and the Stack Trace for you.

```PHP
Error
PHP Fatal Error – yii\base\ErrorException

Undefined class constant 'humhub\modules\user\models\User::USERGROUP_USER'
1. in /usr/share/nginx/dev-store/modules/mail/Events.php at line 79
707172737475767778798081828384858687            return;
        }
 
        $event->sender->addWidget(Notifications::className(), array(), array('sortOrder' => 90));
    }
 
    public static function onProfileHeaderControlsInit($event)
    {
        $profileUser = $event->sender->user;
        $notPermitted = version_compare(Yii::$app->version, '1.1', '>=') && !$profileUser->getPermissionManager()->can(new SendMail());
        if (Yii::$app->user->isGuest || $profileUser->id == Yii::$app->user->id || $notPermitted) {
            return;
        }
 
        $event->sender->addWidget(NewMessageButton::className(), array('guid' => $event->sender->user->guid, 'type' => 'info'), array('sortOrder' => 90));
    }
 
}
2. yii\base\ErrorHandler::handleFatalError()
$_GET = [
    'uguid' => 'b97af8c6-4071-4e99-981b-6a16c4a87833',
];

$_COOKIE = [
    'language' => '75d660b956e116b807fa2c8846ef36f04a0d9683f57ba50cf4eb2b41abf6f7d6a:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    'PHPSESSID' => 'd109qoe6vfh5rt46p78fuq2c60',
    '_csrf' => '7fcd70d2312aac2a7477ac557e1a27331c76aae0717bf6fd26ce0d6700eede2da:2:{i:0;s:5:"_csrf";i:1;s:32:"7eSgwy2Y8IMUba7Q6CvgMEPxzSY5FJyz";}',
    'pm_getting-started-panel' => 'expanded',
    'pm_share-panel' => 'expanded',
    '_ga' => 'GA1.2.1104217995.1461335691',
    '_identity' => '5d1f3790eeac3cf54e09a98e756c3a9acb5e81e3d4773366530f59dda7f45853a:2:{i:0;s:9:"_identity";i:1;s:50:"[1,"b97af8c6-4071-4e99-981b-6a16c4a87833",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 1,
];
Yii Framework
2016-07-15, 13:33:28

nginx/1.8.1
Yii Framework/2.0.9
```

```PHP
2016-07-15 13:33:28 [72.91.43.34][1][d109qoe6vfh5rt46p78fuq2c60][error][yii\base\ErrorException:1] exception 'yii\base\ErrorException' with message 'Undefined class constant 'humhub\modules\user\models\User::USERGROUP_USER'' in /usr/share/nginx/dev-store/modules/mail/Events.php:79
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
2016-07-15 13:33:27 [72.91.43.34][1][d109qoe6vfh5rt46p78fuq2c60][info][application] $_GET = [
    'uguid' => 'b97af8c6-4071-4e99-981b-6a16c4a87833'
]
```

**Comment by buddha87** [comment]
Please check under "Administration -> About" if the right humhub version is displayed.

**Comment by davidjeddy** [comment]
![screen shot 2016-07-15 at 2 29 01 pm](https://cloud.githubusercontent.com/assets/6232455/16884644/812b9ebc-4a98-11e6-97a0-e99b828bf313.png)

Our application is based on the 'stable' HumHub branch (hash: cac76c9aa9c2b6791abf521af7b33e4e11f305f5), if that helps.

**Comment by buddha87** [comment]
Very strange, the faulty condition should normally not be executed in versions lower than 1.1. Perhaps this is a php version issue.
I've changed the affected line in here on this branch https://github.com/buddha87/humhub-modules-mail

Would be great if you can test this version in your environment, since I can't reproduce the this issue.

**Comment by davidjeddy** [comment]
So I found what is causing this issue. The application we are working on is located in ./protected/appName. Said app is loaded in index.php after HumHub. This the configuration will overwrite or expand on that of humhub...including the version number. The App is at version 1.1.1 and about to reach 1.2.0, this is ahead of HumHubs version of course.

So, the mail module was fine all along, would recommend using a different indicator other than $app->version as any project that is based on HumHub will likely run there own semver counter.

Side note: thank you for the hjelp on this! +1
