### ISSUE TITLE
Auto scroll down to latest message

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub-modules-mail#109]
Chat does not scroll down to the latest message, after clicking on the entry in the new message notification.

**Comment by ShalokShalom** [comment]
Will this happen in 1.2?

**Comment by buddh4** [comment]
The feature is not implemented yet, but it's planned to revisit the mail module soon.

**Comment by 3cst4sy** [comment]
#121 Take a look

**Comment by buddh4** [comment]
@3cst4sy thanks we'll have a look at all PRs within the next days, thanks for the contibution

**Comment by 001101** [comment]
What about a merge?
