### ISSUE TITLE
Userpicker in mail-module doesn't work (in MeetingManager as well not)

### ISSUE THREAD

**Issue by Zanzibari** [humhub/humhub-modules-mail#110]
can't figure-out how else wise to address somebody

**Comment by buddh4** [comment]
Are there any errors, is the userpicker displayed, doesn't it load users? Please describe your problem in more detail and check for errors in your logs "Administration -> Information -> Logging"

**Comment by Zanzibari** [comment]
Userpicker displays names, yes.  Let's say I type "pat" and Paternus Niyegira appears: 
`javascript:$.fn.userpicker.addUserTag('85009cfd-9f93-48e8-af1e-e5c5ac7efd7c',%20'/img/default_user.jpg',%20'Paternus%20%20Niyegira',%20'recipient');`

But clicking on them doesn't select anything. No way to pick the addressee :-(

No logging entry, as process had to be aborted. 

Different browsers/servers, same issue. 

If u like, I can send u user-invite with administrator rights. But same issue occurred @ http://ganzkompliziert.humhub.com/ 
the "official" server.

**Comment by buddh4** [comment]
If you've activated the friendship system, your users have to enable receiving messages from non friend users, the default setting can currently not be changed, but this hopefully will change soon. But this should not affect the meeting manager.

**Comment by Buliwyfa** [comment]
will be really nice if this can be fixed or the setting change to allow mail for everyone and then user restricted only to friends if they want more privacy.
