### ISSUE TITLE
 Mail module (latest) does not follow user's security settings

### ISSUE THREAD

**Issue by binarynos** [humhub/humhub-modules-mail#111]
If I go to Account settings> Security> send mail and deny users from sending me mails, users still can send me mails

**Comment by buddh4** [comment]
Could not recreate this issue, if user A disallows other members to send messages. User A is disabled in my userpicker and can't be selected.

Please get sure your security settings are really saved (reload by F5) after changing a value. Unfortunately the user feedback is not given in v1.1 in this case.

**Comment by binarynos** [comment]
This maybe somehow related to the cache issue. After clearing the cache and reloading, the setting gets applied and it works.
Thanks
