### ISSUE TITLE
Message Non-Friend from Profile Page

### ISSUE THREAD

**Issue by FHeaney** [humhub/humhub-modules-mail#123]
After selecting "Enable User Friendship Feature" in humhub v1.2.0, it appears you should only be able to send a message through the mail module to confirmed or pending friendship requests. However, if you go to a users profile and click "Send Message", it will send that user a message regardless of friendship status.

**Comment by buddh4** [comment]
This should only work as system admin, for beeing able to send messages to everyone if required.

**Comment by FHeaney** [comment]
Verified this is the case using a non-admin user.  Thanks for taking a look.

**Comment by tokao** [comment]
Why is this closed? Is a big issue...
