### ISSUE TITLE
Why "updated_at" is populated?

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub-modules-mail#125]
I'm working a little on this module and have noticed that `updated_at` field is populated with the same timestamp than `created_at` at message creation.

I would like to use this value if `!= null` but as it is never null, i can't do it...

Any reason for this?

**Comment by buddh4** [comment]
The field is set [here](https://github.com/humhub/humhub/blob/master/protected/humhub/components/ActiveRecord.php#L44), to check if the content was updated you could use:

```
if (!empty($model->updated_at) && $model->updated_at != $model->created_at)
```

**Comment by acs-ferreira** [comment]
Great thanks. :)

**Comment by acs-ferreira** [comment]
Ok, i've created a simple snippet, but it outputs nothing:

```
<?php if (!empty($model->updated_at) && $model->updated_at != $model->created_at) : ?>
  &middot; <span class="tt" title="<?= Yii::$app->formatter->asDateTime($model->updated_at); ?>"><?= Yii::t('ContentModule.base', 'Updated'); ?></span>
<?php endif; ?>
```

Am i doing it wrong?

**Comment by acs-ferreira** [comment]
This works (`$entry`, not `$model`):

```
<?php if (!empty($entry->updated_at) && $entry->updated_at != $entry->created_at) : ?>
    &middot; <span class="tt" title="<?= Yii::$app->formatter->asDateTime($entry->updated_at); ?>"><?= Yii::t('ContentModule.base', 'Updated'); ?></span>
<?php endif; ?>
```
