### ISSUE TITLE
Special Characters error on email notifications

### ISSUE THREAD

**Issue by Frank1751** [humhub/humhub-modules-mail#133]
Hi,

i have grop with ' in the name title. When it send the notification mail, an unforeseeable character is generated in the object. Is this problem solved?

example : {Originator} vient d'écrire la publication "Quelques photos du futur plateau technique de..." dans l'espace P&#039;tit Bio7Suggérer une modification

i heve found this code

`<?php
return array (
  '{originator} just wrote {contentInfo}' => '{Originator} vient d\'écrire {contentInfo}',
  '{originator} just wrote {contentInfo} in space {space}' => '**{Originator} vient d\'écrire {contentInfo} dans l\'espace {space}**
Suggérer une modification
',
  '{originator} notifies you about {contentInfo}' => '{Originator} vous informe sur {contentInfo}',
  '{originator} notifies you about {contentInfo} in {space}' => '{Originator} vous informe de {contentInfo} dans l\'espace {space}',
);`

does anyone know how to solve it?

thanks.

**Comment by buddh4** [comment]
Don't get whats wrong do you get an error or does this break the syntax of the translation file?
Please use the suggested Issue Template next time, and describe whats actually happening.
