### ISSUE TITLE
undefinied is not a function 

### ISSUE THREAD

**Issue by ShalokShalom** [humhub/humhub-modules-mail#134]
When I open mail for the first time in my test setup and try to compose a message:

TypeError: undefined is not a function (evaluating '$('#recipient').userpicker')
j@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:29:22474
add@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:29:22767
ready@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:29:24853
eval code
eval@[native code]
globalEval@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:19:14483
w@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:19:4597
append@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:30:6067
setDialog@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:259:31857
https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:260:2941
d@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:216:9375
_settlePromiseFromHandler@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:215:14716
_settlePromise@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:215:15537
_settlePromise0@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:215:16225
_settlePromises@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:215:17554
_drainQueue@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:214:3059
_drainQueues@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:214:3116
drainQueues@https://cosmos2.humhub.com/static/js/all-80cc587bf42b9f4207d602b7bba9bd46.js?v=1513202056:214:1238

**Comment by ShalokShalom** [comment]
? oO

**Comment by buddh4** [comment]
The module was reworked in v 1.0.0. Is this still an issue in your installation, which HumHub version and which Module Version are you using?

**Comment by ShalokShalom** [comment]
I have this installation not anymore
