### ISSUE TITLE
[Warning] Inconvenient communication of long dialogues

### ISSUE THREAD

**Issue by towuk118** [humhub/humhub-modules-mail#137]
recent posts at the top and the old bottom.
please add the ability to sort the messages to make it easier to write and not to scroll down and then write the message
![image](https://user-images.githubusercontent.com/28830162/39665123-a48743be-5097-11e8-91da-11a6885981c5.png)

**Comment by AlexaBoe** [comment]
I support this change! We'd be very happy with a rearrangement of the messages.

**Comment by buddh4** [comment]
The module needs a general rework. It's definetly one of the next modules which will be reworked for the purpose of better usability with more ajax, pagination (auto loading) better layout etc. Feel free to open further issues with ideas etc.
