### ISSUE TITLE
Looking for the dev of the humhub mail module

### ISSUE THREAD

**Issue by deehill** [humhub/humhub-modules-mail#146]
Hi Andy,

Saw you created a module for humhub and thought I'd ask If you might be interested in doing some dev/mods for a version of humhub for me. I'm looking to strip out a bunch of functionality, and add a few functions for an app that I need. Humhub would essentially be a shell. 

I basically need an app where users can join a "community" and in turn invite others to join. There will be the usual groups for users to join, as well as a section where users can see the "growth" of the different groups, and overall community. There's some other stuff, but nothing that's too complex/difficult. 

I'm looking to talk to someone who's already got a feel for humhub, as this will save me time.

If you're interested, hit me up.

thanks

-bruce

**Comment by danielkesselberg** [comment]
I hope its okay for you that i close this issue. You can find the contributors for each a very easily on github. 
![image](https://user-images.githubusercontent.com/3902676/45634465-c822eb00-baa2-11e8-8e68-aeeaf39756cd.png)
