### ISSUE TITLE
Button looks bad since last update

### ISSUE THREAD

**Issue by xaro1** [humhub/humhub-modules-mail#147]
![screen shot 2018-09-28 at 13 56 16](https://user-images.githubusercontent.com/6691309/46207109-7e4dc680-c326-11e8-9c7d-43aa1a4f1e2d.png)

**Comment by xaro1** [comment]
Since 1.0.1 and 1.0.2

**Comment by xaro1** [comment]
I think you have found a workaround but this issue is **not** truly resolved.

Since, 1.0.3, button height is Ok but there is no more padding at left side like before and icon has disappeared.

**Comment by buddh4** [comment]
You are right I did not test this with friendship active thanks for the note.
