### ISSUE TITLE
Cannot read property 'timeout' of undefined

### ISSUE THREAD

**Issue by dmitrydrynov** [humhub/humhub-modules-mail#148]
I have error on click to
![image](https://user-images.githubusercontent.com/4089575/46693274-ffa03580-cc11-11e8-8776-5c7163cd3e6b.png)

```
TypeError: Cannot read property 'timeout' of undefinedTypeError: Cannot read property 'timeout' of undefined
    at Object.redirect (https://campus.polygon.by/static/js/humhub/humhub.client.pjax.js?v=1538086224:23:95)
    at Object.loadMessage (https://campus.polygon.by/assets/439405d8/js/humhub.mail.wall.js?v=1539112376:283:25)
    at _executeAction (https://campus.polygon.by/static/js/humhub/humhub.action.js?v=1538086224:430:35)
    at ActionBinding.handle (https://campus.polygon.by/static/js/humhub/humhub.action.js?v=1538086224:403:17)
    at HTMLAnchorElement. (https://campus.polygon.by/static/js/humhub/humhub.action.js?v=1538086224:623:27)
    at HTMLDocument.dispatch (https://campus.polygon.by/assets/4fbc429f/jquery.js?v=1539112459:5206:27)
    at HTMLDocument.elemData.handle (https://campus.polygon.by/assets/4fbc429f/jquery.js?v=1539112459:5014:28)
```

**Comment by buddh4** [comment]
Is there any other error prior to this and does everything else work as expected?

**Comment by dmitrydrynov** [comment]
No, only this

**Comment by dmitrydrynov** [comment]
I solved this problem. I enabled pjax in a configure file. (before I disable it)

**Comment by vandenbos** [comment]
@buddh4 I am also getting this, I have raised a bug.

**Comment by vpadhariya** [comment]
Hi Team, I am also getting this bug, any update on this fix?

Debug messages
`humhub.log.js?v=1554701501:160 DEBUG - humhub.modules.action: Detected unhandled action ActionBinding {parent: document, eventType: "click", event: "click.humhub-action", selector: "[data-action-click]", directHandler: undefined, …}`

`humhub.log.js?v=1554701501:162 DEBUG - humhub.modules.action: Update action bindings`

`humhub.log.js?v=1554701501:160 DEBUG - humhub.modules.action: Handle Action ActionBinding {parent: document, eventType: "click", event: "click.humhub-action", selector: "[data-action-click]", directHandler: undefined, …}`

Error Message
`humhub.log.js?v=1554701501:160 DEBUG - humhub.modules.action: Detected unhandled action ActionBinding {parent: document, eventType: "click", event: "click.humhub-action", selector: "[data-action-click]", directHandler: undefined, …}
humhub.log.js?v=1554701501:162 DEBUG - humhub.modules.action: Update action bindings
humhub.log.js?v=1554701501:160 DEBUG - humhub.modules.action: Handle Action ActionBinding {parent: document, eventType: "click", event: "click.humhub-action", selector: "[data-action-click]", directHandler: undefined, …}`

1. I just updated the Humhub mail module to latest version 1.0.12
2. Installed Humhub version is 1.3.13-pre

Please help, thanks

**Comment by vpadhariya** [comment]
Thanks, finally solved this out by overwriting template.

###Solution

Move following template

`@humhub/modules/mail/views/mail/_messagePreview.php`

to

`@themes/views/mail/mail/_messagePreview.php`

and replace the line 

`<a href="#" class="mail-link" data-action-click="mail.wall.loadMessage" data-action-url="<?= Url::to(['/mail/mail', 'id' => $message->id])?>" data-message-id="<?= $message->id ?>">`

With

`<a href="<?= Url::to(['/mail/mail', 'id' => $message->id])?>" class="mail-link" data-message-id="<?= $message->id ?>">`

and Issue finally solved for me.

NOTE: this is nothing but `href` method instead of `$.pjax`, as `$.pjax` shows undefined and not sure how to solve it!

**Comment by buddh4** [comment]
@vpadhariya @vandenbos do you both have pjax disabled?

**Comment by vpadhariya** [comment]
@buddh4 yes, I have pjax disabled.

1. I enabled pjax, 
2. flush cache, 
3. rebuild assets 

still error persist so finally I think to over write the template file.

**Comment by tmthan** [comment]
I have fix this bug. The solution is enable pajax:
Go to protected/config/conmmon.php
find "pajax=false" and modify property from "false" to "true"
