### ISSUE TITLE
Mail Duplication in Display

### ISSUE THREAD

**Issue by Felli** [humhub/humhub-modules-mail#155]
See community [post](https://community.humhub.com/s/contribution-core-development/?contentId=182653) for more information on how to reproduce.

**Comment by buddh4** [comment]
There are no infos on how to reproduce?

**Comment by Felli** [comment]
The post over on the community said to click the mail icon over and over again to show the issue which I can confirm on the community side that it duplicates every message you have displayed in the dropdown.

**Comment by buddh4** [comment]
Thanks, for the clarification.
