### ISSUE TITLE
new messages show date of  Jan 1, 1970 until refreshed

### ISSUE THREAD

**Issue by zogith** [humhub/humhub-modules-mail#175]
When a new message is created, the date is shown as Jan 1, 1970
Once the screen is refreshed or another humhub mail message appears, the date shows when it was posted as it should.
This appears on my self hosted instance with HumHub 1.4.4 and humhub mail 1.0.15 - other users have mentioned this to me as well, so I doubt it is browser specific.

It also shows on https://community.humhub.com/ - log into there and send a message to someone to reproduce.

Example screenshot from  https://community.humhub.com/ showing the issue:

![Screenshot_2020-04-12_02-14-11](https://user-images.githubusercontent.com/7069599/79048983-2d7d9480-7c64-11ea-87b4-4c34298715ec.png)

**Comment by funkycram** [comment]
Same for me (Humhub 1.4.4, but since Humhub 1.3 if I remember well)

**Comment by buddh4** [comment]
Fixed in 2.0 which is currently in beta.
