### ISSUE TITLE
Message not scrolled down completely

### ISSUE THREAD

**Issue by JK742020** [humhub/humhub-modules-mail#198]
When opening a conversation with many messages inside sometimes the conversation is not scrolled down completely. I have to scroll down to read the last message sent. Sometimes it stucks at a picture sometimes on text quite randomly. Now I tried to reproduce it. First time when entering the conversation from letter-symbol -> certain conversation it stuck again. Second time it was not possible to reproduce.

**Comment by buddh4** [comment]
This happens probably if the auto scroll happens after images are fully loaded.

**Comment by JK742020** [comment]
that makes sense!
