### ISSUE TITLE
Empty text box sending problem

### ISSUE THREAD

**Issue by Vatarus** [humhub/humhub-modules-mail#2]
If you press the button "Send" while the text box is empty, then get an template error. (see screens)
![messagemodule_issue_1](https://cloud.githubusercontent.com/assets/3394915/4296278/83e0606e-3df4-11e4-9989-394b12bc20c1.png)
![messagemodule_issue_2](https://cloud.githubusercontent.com/assets/3394915/4296277/83ddc336-3df4-11e4-8869-4ba623dd092a.png)

**Comment by jirimedved** [comment]
Hey, any progress? Thanks
