### ISSUE TITLE
2.0.0 on HumHub 1.6.3

### ISSUE THREAD

**Issue by bountin** [humhub/humhub-modules-mail#201]
I received the following error on 1.6.3. After the upgrade to 1.6.4 the error went away.

```
yii\base\UnknownPropertyException: Setting unknown property: humhub\modules\mail\widgets\NewMessageButton::right in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('right', true)
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(humhub\modules\mail\widgets\NewMessageButton), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#6 /var/www/humhub/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject(Array)
#7 /var/www/humhub/protected/modules/mail/widgets/views/notificationInbox.php(24): humhub\components\Widget::widget(Array)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/hum...')
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/hum...', Array)
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/hum...', Array, Object(humhub\modules\mail\widgets\NotificationInbox))
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('notificationInb...', Array, Object(humhub\modules\mail\widgets\NotificationInbox))
#12 /var/www/humhub/protected/modules/mail/widgets/NotificationInbox.php(20): yii\base\Widget->render('notificationInb...', Array)
#13 /var/www/humhub/protected/humhub/components/Widget.php(63): humhub\modules\mail\widgets\NotificationInbox->run()
#14 /var/www/humhub/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array)
#15 /var/www/humhub/protected/humhub/components/Widget.php(63): humhub\widgets\BaseStack->run()
#16 /var/www/humhub/protected/humhub/views/layouts/main.php(32): humhub\components\Widget::widget()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/hum...')
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/hum...', Array)
#19 /var/www/humhub/protected/humhub/components/Controller.php(136): yii\base\View->renderFile('/var/www/hum...', Array, Object(humhub\modules\marketplace\controllers\BrowseController))
#20 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(410): humhub\components\Controller->renderContent('<div class="con...')
#21 /var/www/humhub/protected/humhub/modules/marketplace/controllers/BrowseController.php(87): yii\base\Controller->render('list', Array)
#22 [internal function]: humhub\modules\marketplace\controllers\BrowseController->actionList()
#23 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#25 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array)
#26 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('marketplace/bro...', Array)
#27 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#28 /var/www/humhub/index.php(25): yii\base\Application->run()
#29 {main}
```

**Comment by aronbos** [comment]
On 1.6.4 I get yii\base\UnknownMethodException: Calling unknown method: humhub\modules\mail\Module::hideInTopNav() in /mypath/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300 Stack trace: #0 /mypath/humhub/protected/modules/mail/Events.php(71): yii\base\Component->__call('hideInTopNav', Array) #1 [internal function]: humhub\modules\mail\Events::onTopMenuInit(Object(yii\base\Event)) #2 /mypath/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event)) #3 /mypath/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('humhub\\widgets\\...', 'init', Object(yii\base\Event)) #4 /mypath/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(72): yii\base\Component->trigger('init') #5 /mypath/humhub/protected/humhub/widgets/TopMenu.php(40): yii\base\Widget->init() #6 /mypath/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\widgets\TopMenu->init() #7 [internal function]: yii\base\BaseObject->__construct(Array) #8 /mypath/humhub/protected/vendor/yiisoft/yii2/di/Container.php(398): ReflectionClass->newInstanceArgs(Array) #9 /mypath/humhub/protected/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('humhub\\widgets\\...', Array, Array) #10 /mypath/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\widgets\\...', Array, Array) #11 /mypath/humhub/protected/humhub/components/Widget.php(60): yii\BaseYii::createObject(Array) #12 /mypath/humhub/themes/Alforto/views/layouts/main.php(69): humhub\components\Widget::widget() #13 /mypath/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/p...') #14 /mypath/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/html/p...', Array) #15 /mypath/humhub/protected/humhub/components/Controller.php(136): yii\base\View->renderFile('/var/www/html/p...', Array, Object(humhub\modules\marketplace\controllers\UpdateController)) #16 /mypath/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(410): humhub\components\Controller->renderContent('<div class="con...') #17 /mypath/humhub/protected/humhub/modules/marketplace/controllers/UpdateController.php(55): yii\base\Controller->render('list', Array) #18 [internal function]: humhub\modules\marketplace\controllers\UpdateController->actionList() #19 /mypath/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #20 /mypath/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #21 /mypath/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('list', Array) #22 /mypath/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('marketplace/upd...', Array) #23 /mypath/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #24 /mypath/humhub/index.php(27): yii\base\Application->run() #25 {main}

**Comment by buddh4** [comment]
Did this only happen once directly after the update? Probably related to https://github.com/humhub/humhub/issues/3872

**Comment by aronbos** [comment]
Yes, once directly after the update.

**Comment by buddh4** [comment]
This error should not affect the module or have any side effects. Its an issue with the module update process.
