### ISSUE TITLE
Error after update: Messages error

### ISSUE THREAD

**Issue by iello** [humhub/humhub-modules-mail#203]
Hi,

After updating HumHub i have the following error when displaying messages:

```yii\base\ErrorException: Trying to get property 'user_id' of non-object in /var/www/html/ciolan.io/protected/modules/mail/models/UserMessage.php:122 Stack trace: #0 /var/www/html/ciolan.io/protected/modules/mail/models/UserMessage.php(122): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/html/c...', 122, Array) humhub/humhub#1 /var/www/html/ciolan.io/protected/modules/mail/widgets/views/inboxMessagePreview.php(25): humhub\modules\mail\models\UserMessage->isUnread() humhub/humhub#2 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/c...') humhub/humhub#3 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/html/c...', Array) humhub/humhub#4 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/c...', Array, Object(humhub\modules\mail\widgets\InboxMessagePreview)) humhub/humhub#5 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('inboxMessagePre...', Array, Object(humhub\modules\mail\widgets\InboxMessagePreview)) humhub/humhub#6 /var/www/html/ciolan.io/protected/modules/mail/widgets/InboxMessagePreview.php(19): yii\base\Widget->render('inboxMessagePre...', Array) humhub/humhub#7 /var/www/html/ciolan.io/protected/humhub/components/Widget.php(63): humhub\modules\mail\widgets\InboxMessagePreview->run() humhub/humhub#8 /var/www/html/ciolan.io/protected/modules/mail/widgets/views/inbox.php(19): humhub\components\Widget::widget(Array) humhub/humhub#9 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/c...') humhub/humhub#10 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/html/c...', Array) humhub/humhub#11 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/c...', Array, Object(humhub\modules\mail\widgets\ConversationInbox)) humhub/humhub#12 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('inbox', Array, Object(humhub\modules\mail\widgets\ConversationInbox)) humhub/humhub#13 /var/www/html/ciolan.io/protected/modules/mail/widgets/ConversationInbox.php(58): yii\base\Widget->render('inbox', Array) humhub/humhub#14 /var/www/html/ciolan.io/protected/humhub/components/Widget.php(63): humhub\modules\mail\widgets\ConversationInbox->run() humhub/humhub#15 /var/www/html/ciolan.io/protected/modules/mail/views/mail/_conversation_sidebar.php(37): humhub\components\Widget::widget(Array) humhub/humhub#16 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/c...') humhub/humhub#17 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/html/c...', Array) humhub/humhub#18 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/c...', Array, NULL) humhub/humhub#19 /var/www/html/ciolan.io/protected/modules/mail/views/mail/index.php(17): yii\base\View->render('_conversation_s...') humhub/humhub#20 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/c...') humhub/humhub#21 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/html/c...', Array) humhub/humhub#22 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/c...', Array, Object(humhub\modules\mail\controllers\MailController)) humhub/humhub#23 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/Controller.php(409): yii\base\View->render('index', Array, Object(humhub\modules\mail\controllers\MailController)) humhub/humhub#24 /var/www/html/ciolan.io/protected/modules/mail/controllers/MailController.php(56): yii\base\Controller->render('index', Array) humhub/humhub#25 [internal function]: humhub\modules\mail\controllers\MailController->actionIndex('12') humhub/humhub#26 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) humhub/humhub#27 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) humhub/humhub#28 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array) humhub/humhub#29 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('mail/mail/index', Array) humhub/humhub#30 /var/www/html/ciolan.io/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) humhub/humhub#31 /var/www/html/ciolan.io/index.php(25): yii\base\Application->run() humhub/humhub#32 {main}```

**Comment by buddh4** [comment]
There is a new module update available, after updating you'll probably have to run the [Data Integrity Check](https://docs.humhub.org/docs/admin/troubleshooting#data-integrity)

**Comment by iello** [comment]
Thanks. All good!
