### ISSUE TITLE
reply to email from messaging system is send to adminstrator

### ISSUE THREAD

**Issue by gerhardbeck** [humhub/humhub-modules-mail#204]
Just controlling the personal data things for the GDPR-Requirements and noticed:
When a message is sent with the messaging system and email notice is on, an email with the personal message is send to the receiver of the message.
if the receiver answers via email (what already happened in my community) the answer is not sent to the sender of the message but to the administrator who has now unintended knowledge of the message.

Possible solutions:

- https://github.com/humhub/humhub-modules-mail/issues/149

- a warning message before the real message text (not secure, but better)

**Comment by buddh4** [comment]
You should configure a `noreply` address in  `Administration -> Settings -> Advanced -> E-Mail -> Sender Address`. Currently there are no mails with a possibility to reply by mail. This should probably be emphasized in the docs.

**Comment by gerhardbeck** [comment]
Thanks a lot.
