### ISSUE TITLE
When sending Message on HumHub

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub-modules-mail#39]
I have not verified this on my build (literally just updated Mail) but on HumHub when I sent a message to @luke- , the page then turned into this

<img src="http://img.prntscr.com/img?url=http://i.imgur.com/3ib640g.png" />

Eventually the page seems to fix itself, but then all jQuery is broken (no dropdown menus work like account dropdown, notification drop down, messages drop down, my spaces dropdown, etc)

**Comment by WASasquatch** [comment]
Nothing? This happens on my builds as well. Page is broken after message sent.

**Comment by WASasquatch** [comment]
So mail module is being left broken?

**Comment by Vatarus** [comment]
+1 
same problem

**Comment by programguy** [comment]
This problem is driving me crazy! The page looks normal, but the dropdowns don't work. Is anyone going to fix this?

**Comment by WASasquatch** [comment]
Yeah it's JS loading through AJAX or something that is breaking the whole site. The latest update to Mail module speeds up this issue, but still after sending a message you have to reload the whole page to use drop-down menus or search. I'm not sure why the JS script is not on the main page, and only loading JSON data to fill HTML tags.
