### ISSUE TITLE
"Send" button shows no feedback

### ISSUE THREAD

**Issue by caspre24** [humhub/humhub-modules-mail#40]
When sending a new message or a message reply, clicking or tapping the "send" button gives no feedback whether the sending is in progress. If a user is impatient he/she might click the button again (and again...) which leads to duplicate messages.

Maybe there could be a waiting spinner or the send button could not accept further clicks after the first one.

**Comment by programguy** [comment]
Yes, please! A lot of my users are sending many duplicate messages.

**Comment by programguy** [comment]
Is no one interested in fixing this? I don't know if I could do a good job myself.
