### ISSUE TITLE
GetMessageCount

### ISSUE THREAD

**Issue by Stranikevg** [humhub/humhub-modules-mail#42]
exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "GetMessageCount".' in /var/www/---/protected/vendors/yii/web/CController.php:483 Stack trace: 
/var/www/---/protected/vendors/yii/web/CController.php(270): CController->missingAction('GetMessageCount')
/var/www/---/protected/vendors/yii/web/CWebApplication.php(282): CController->run('GetMessageCount') 
/var/www/---/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('mail/mail/GetMe...') /var/www/---/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() 
/var/www/---/index.php(39): CApplication->run() 5 {main} REQUEST_URI=/mail/mail/GetMessageCount?CSRF_TOKEN=7a6bc66794310070e72ae5f78b6201b77c3b7635&_=1428907512447 HTTP_REFERER=http://---.ru/dashboard ---

and

http://---/mail/mail/index/ 

ops - delet 
https://github.com/humhub/humhub/commit/26780cada192c250a3558ed6c98c36c221a2a78b

**Comment by JeXawoW** [comment]
@Stranikevg php 5.4.+
![222](https://cloud.githubusercontent.com/assets/7725575/7111494/224ba1aa-e1c9-11e4-9e9f-c0a9ab629f3f.PNG)

**Comment by jkuchar** [comment]
Hit F5 (refresh page) after upgrade in all clients. ;-) We had this issue too.
