### ISSUE TITLE
mail module hang when i try to send new mail

### ISSUE THREAD

**Issue by yatno** [humhub/humhub-modules-mail#50]
Hi, 

I dont know, its happened only to me or its happen to you too.
i cant send mail. its only hang when i click send button.

![screenshot from 2015-06-17 15-56-05](https://cloud.githubusercontent.com/assets/10286104/8203068/6a0c2b18-1509-11e5-8d31-5fd5f12bd726.png)

and when i click show all messages, it show a form that not contain css. see screenshoot below.

![screenshot from 2015-06-17 15-53-27](https://cloud.githubusercontent.com/assets/10286104/8203029/28f35caa-1509-11e5-8cd9-3ee53216253b.png)

![screenshot from 2015-06-17 15-44-26](https://cloud.githubusercontent.com/assets/10286104/8202894/18a94f9a-1508-11e5-9803-c3bb45f2b257.png)

**Comment by GallandJe** [comment]
Hello,

I've exactly the same problem... Here is a screen capture of the chrome's console when i click on a notif : 
![bug-humhub](https://cloud.githubusercontent.com/assets/12172206/8240620/4c03415a-1604-11e5-9254-e799b46958b4.jpg)

I'm on a CentOS server (if that can help)

**Comment by IceSweets** [comment]
Hello, did you fix it ?

**Comment by luke-** [comment]
Maybe a problem with your PHP Version?

We need at least PHP 5.4

https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/requirements.md

**Comment by GallandJe** [comment]
Hi,

I confirm that's a PHP's version problem. Update PHP solved the problem for me.

thanks @luke-
