### ISSUE TITLE
Messages.

### ISSUE THREAD

**Issue by helpACS** [humhub/humhub-modules-mail#55]
Issue 1:
When a user creates a message and tries to send, the message sends, but the message remains on screen as if the send button was never clicked. However, if the person clicks send 22 times (this was accidentally tested this way), the message will send 22 times, and the receiver will get 22 messages.
###### 

Issue 2: 
When the user clicks the envelope to go to their messages, their messages are displayed, however, all messages listed in the new page are dead. They will click and turn purple as if it has been clicked, but go no further. Pop Up blockers are off.
###### 

Issue 3:
If from within the listing of new messages the person clicks send new message, the user is presented with a 'unformatted' page of html text box, and buttons. While the text boxes will receive data, the buttons do not send.

**Comment by Tcex** [comment]
This problem I have, messages are called in a new white page. There they are listed.
![screen](https://cloud.githubusercontent.com/assets/13807792/9288212/5099bf46-433b-11e5-91d4-c7ec35666e00.png)

**Comment by Mazux** [comment]
I've got that problem too and I can't fix it.

The module works fine when I use the Humhub local testing site with my demo version, but not on my site. I'd really like this fixed.

**Comment by Tcex** [comment]
I solved the problem. Now I have installed myself on my server php 5.6.12

**Comment by helpACS** [comment]
Yes this is fixed with your php version at least 5.6 or higher for the site.

Thank you for your time.
Respectfully,
John Walsh
President & Chairman
ACS Inc
832-429-4223<tel:832-429-4223> Corp
832-460-9483<tel:832-460-9483> Fax
315-352-0444<tel:315-352-0444> Office
