### ISSUE TITLE
Options to Report & Disable for members

### ISSUE THREAD

**Issue by Felli** [humhub/humhub-modules-mail#72]
An option for disabling the mail module for a member without having to disable the whole module would be nice and useful thing to be added.
## Example

Someone is abusing the module's function by either spamming, harassing, or bullying someone, allowing someone to report this to a staff member with the power (site side) to disable the module for the reported person is needed.

**Comment by buddh4** [comment]
I think we'd need a general blocking mechanism not only for the mail module.
