### ISSUE TITLE
New message - no address selection possible

### ISSUE THREAD

**Issue by JoergKirn** [humhub/humhub-modules-mail#81]
Since the last update there is no more addressing of people in the message window possible - the quick search does not work, it is only the list of the first user is displayed and only these can be selected. Even the full name entered does not allow to select a specific user.

**Comment by buddha87** [comment]
Which humhub version are you using ?

**Comment by JoergKirn** [comment]
Version: 1.0.0-beta.4

**Comment by buddha87** [comment]
Could you please update the mail module and check if the problem is solved ?

**Comment by JoergKirn** [comment]
the Mail module is in version 0.8.0... and I have no chance to update... - only deactivate / deinstall....

**Comment by buddha87** [comment]
Hmm probably you have to flush the cache to see the new version: Administration -> Caching -> Flush Cache. Then ther should be a new version 0.8.2.

**Comment by JoergKirn** [comment]
updated to 0.8.2 - Mail addressing works again :+1:
