### ISSUE TITLE
BUG: Submitting mail without populating fields returns ajax module w/o view

### ISSUE THREAD

**Issue by davidjeddy** [humhub/humhub-modules-mail#83]
![screen shot 2016-03-30 at 15 48 16](https://cloud.githubusercontent.com/assets/6232455/14155118/516295e0-f68e-11e5-830f-0b8b8aaed3b0.png)

Submit that empty, the response is as follows:
![screen shot 2016-03-30 at 15 50 02](https://cloud.githubusercontent.com/assets/6232455/14155133/642e016e-f68e-11e5-809d-801a7efd8da2.png)

**Comment by buddha87** [comment]
Hi, which humhub version do you use ? This should be fixed in version 1.0.

**Comment by 3cst4sy** [comment]
Check my pull request #82

**Comment by davidjeddy** [comment]
@3cst4sy fix looks like it would correct the issue.
