### ISSUE TITLE
Bug: Markdown Backquotes

### ISSUE THREAD

**Issue by Felli** [humhub/humhub-modules-mail#86]
Within the mail module there is a slight bug with the markdown backquotes, they don't work.
### Example

![screenshot_3](https://cloud.githubusercontent.com/assets/2011633/14370562/55f848d2-fcfd-11e5-819c-0a6e5dc111c6.png)

_Will add a better screenshot later..._

**Comment by Felli** [comment]
Used from a conversation on https://community.humhub.com
![](http://image.prntscr.com/image/4c43d30293c14bb4afd8d3cc6304bb1c.png)

**Comment by buddh4** [comment]
Thanks, seems to be an issue with the markdown parser, same happens in wikis.
