### ISSUE TITLE
Bug: Send email button does not change the view

### ISSUE THREAD

**Issue by Gaetano666** [humhub/humhub-modules-mail#92]
When you press the Send button after writing an email, the email remains in edit mode, instead of showing the mail as sent.
The email itself it is sent, but to the user it seems the "Send" button did not work.
this cause the user to resend the email sefveral times :(
Gaetano

**Comment by buddha87** [comment]
Did this happen in v1.1 ?

**Comment by Gaetano666** [comment]
this is happening on the HH community (https://community.humhub.com/) so I imagine it is the latest version.
some weeks ago this was not happening
Gaetano

**Comment by buddha87** [comment]
Yes we updated the community to v1.1 we already aware of that issue, thanks. Will be fixed before going beta :)

**Comment by Gaetano666** [comment]
ok, perfect! I'll close this issue so.
cheers,
Gaetano
