### ISSUE TITLE
notifications don't disapear and messages panel doesn't show up (Version:0.9.0)

### ISSUE THREAD

**Issue by ghost** [humhub/humhub-modules-mail#93]
I don't know if problem is from the module or from updating Humhub to v1.1.0-beta.1

Notifications of new messages never disapear
going to Messages, only left panel shows up, and clicking on a conversation won't do anything.
After that, if you try to send a message,typing first 3 letters of a name not always shows the name of member.

I am sorry, i am not a techie, I described the problem the best I could.

**Comment by buddha87** [comment]
Is there any error in the developer tools of your browser when you click on a notification ?
