### ISSUE TITLE
Could not send notification e-mail to: Error:Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub-modules-mail#94]
$_SERVER = [ 'PATH' => '/sbin:/usr/sbin:/bin:/usr/bin' 'PWD' => '/usr/local/cpanel/cgi-sys' 'SHLVL' => '0' 'PHP_FCGI_MAX_REQUESTS' => '5000' 'SCRIPT_NAME' => '/index.php' 'REQUEST_URI' => '/mail/mail/create' 'QUERY_STRING' => '' 'REQUEST_METHOD' => 'POST' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'REDIRECT_URL' => '/mail/mail/create' 'REMOTE_PORT' => '57646' 'SCRIPT_FILENAME' => '/home/hhrpadmin/public_html/index.php' 'SERVER_ADMIN' => 'webmaster@humhub.rapidpage.ca' 'CONTEXT_DOCUMENT_ROOT' => '/home/hhrpadmin/public_html' 'CONTEXT_PREFIX' => '' 'REQUEST_SCHEME' => 'http' 'DOCUMENT_ROOT' => '/home/hhrpadmin/public_html' 'REMOTE_ADDR' => '216.240.7.170' 'SERVER_PORT' => '80' 'SERVER_ADDR' => '107.180.56.141' 'SERVER_NAME' => 'humhub.rapidpage.ca' 'SERVER_SOFTWARE' => 'Apache/2.4.18' 'SERVER_SIGNATURE' => '' 'LD_LIBRARY_PATH' => '/usr/local/apache/lib' 'HTTP_COOKIE' => 'pm_getting-started-panel=expanded; pm_share-panel=expanded; _pk_id.2.f697=f0f92eecfb2c2bb2.1464879884.1.1464879884.1464879884.; __utma=31464765.162507091.1464879884.1464879884.1464879884.1; __utmc=31464765; __utmz=31464765.1464879884.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _csrf=3eabd27b527f2e43b5f697cb410f01a653f1be990e5afd777bced95648afe8e8a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22FZYKA4j0PJp7EqqJE-lTIcpKkrXl1GcV%22%3B%7D; language=90e28592f4c58ea34b2d119c6604b5099580834ad6c9ef7b57c2de59aa403584a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; PHPSESSID=287f3df27d84c14353161542c2885ad7; _pk_id.8.6fbd=ec7474bb0f29b56e.1464616060.15.1465247878.1465245465.; _pk_ses.8.6fbd=*; _identity=f3482bddb20ccea9e0b94a1cf718ad49db97beaa1700d46c4cff120f6889c7e2a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%225bbe247e-2411-4ff7-aab6-8413d647afdb%22%2C2592000%5D%22%3B%7D' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate' 'HTTP_REFERER' => 'http://humhub.rapidpage.ca/admin/logging' 'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => 'SDdXaS52NjMObQ4ib0JcAxh9J15rB0d5DRo7PWcVRngjRQ8FHzFVZQ==' 'HTTP_ORIGIN' => 'http://humhub.rapidpage.ca' 'HTTP_ACCEPT' => '*/*' 'CONTENT_LENGTH' => '228' 'HTTP_CONNECTION' => 'close' 'HTTP_HOST' => 'humhub.rapidpage.ca' 'UNIQUE_ID' => 'V1XomMZH7DYADRJHVjsAAAIT' 'REDIRECT_STATUS' => '200' 'REDIRECT_UNIQUE_ID' => 'V1XomMZH7DYADRJHVjsAAAIT' 'FCGI_ROLE' => 'RESPONDER' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1465247896.9116 'REQUEST_TIME' => 1465247896 ]

**Comment by rapidpage** [comment]
I updated the new branch, however, same issue.

**Comment by buddha87** [comment]
Hi the given log is just the request log of an error there should be an additional error log.

**Comment by rapidpage** [comment]
Hi,
Where would i get that error log?

**Comment by rapidpage** [comment]
exception 'yii\base\ErrorException' with message 'Call to undefined method humhub\modules\user\models\Setting::findAll()' in /home/hhrpadmin/public_html/protected/modules/breakingnews/controllers/AdminController.php:35 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}

**Comment by rapidpage** [comment]
I think that my entire setup is broken...

**Comment by buddha87** [comment]
Have you updated your installation recently ? And which version is installed ? I think the sender email address cannot be determined which could be an update issue.

**Comment by buddha87** [comment]
And please check if you can update the mailer module the latest version should be 0.9.0

**Comment by rapidpage** [comment]
Ya, i recently did an update to beta 1.1 and yes the mailer module is 0.9.0

**Comment by rapidpage** [comment]
Currently installed version: 1.1.0-beta.1
Mail Version: 0.9.0

**Comment by rapidpage** [comment]
I did a complete reinstall and same issue: Could not send notification e-mail to: Val Boquiren. Error:Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

**Comment by buddha87** [comment]
There should be a new mail version available (0.9.1) could you please check if this fixes your issue.

**Comment by rapidpage** [comment]
looks fine, however, have another issue.
