### ISSUE TITLE
New conversation members are greyed out

### ISSUE THREAD

**Issue by Twilek-de** [humhub/humhub-modules-mail#95]
When trying to add new members to a conversation I can see them
![recipient](https://cloud.githubusercontent.com/assets/8283684/15849335/39e2a9fc-2c92-11e6-816c-4a97bfd1500a.png) but they are greyed out and cannot be selected. Is that intentional or a bug?

**Comment by Twilek-de** [comment]
When turning off the friendship system, I can add new members again. If that is intentional please make it clear why users cannot be selected.

**Comment by buddha87** [comment]
By default users have to allow messages from non friends in there security settings if the friendship system is enabled.

**Comment by Twilek-de** [comment]
Ah ok, thanks for the clarification. It is not easy to find out what the friendship system really does.

**Comment by 001101** [comment]
It should definitly be disabled for Admin Users!

**Comment by buddha87** [comment]
@001101 yes you are right, is on the todo list.

**Comment by buddha87** [comment]
Furthermore, it would be great if they are not greyed out but if there opens a modal with send friend request instead, or something or at least some infos that the user does not accept messages.

**Comment by 001101** [comment]
It just should be disabled for admins and it would be better to make a blacklist and not a whitelist system, it just makes no sense for a community if you have to be friends to write messages, thats not normal.

**Comment by buddha87** [comment]
The latest update allows system admins to use the 'Send Message' button in the profile view.

**Comment by 001101** [comment]
Not working
