### ISSUE TITLE
@ function no longer works

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub-modules-mail#96]
when I use the @ function to notify a user it does not display the user...

**Comment by rapidpage** [comment]
here are the error codes:
exception 'yii\base\Exception' with message 'Could not get contents underlying object!' in /home/hhrpadmin/public_html/protected/humhub/modules/content/components/actions/Stream.php:243 Stack trace: #0 [internal function]: humhub\modules\content\components\actions\Stream->run() #1 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #2 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #3 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #4 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('space/space/str...', Array) #5 /home/hhrpadmin/public_html/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /home/hhrpadmin/public_html/index.php(25): yii\base\Application->run() #7 {main}
error code:
Underlying object class humhub\modules\linklist\models\Link not found!

**Comment by buddha87** [comment]
Did you delete the Link module without deinstalling it ?

**Comment by rapidpage** [comment]
yes i did, oh boy, what can i do now?

**Comment by rapidpage** [comment]
K, fixed that, now any ideas why when using @ in the comments it asks for 3 letters but no user name appears?
![image](https://cloud.githubusercontent.com/assets/8636793/15929139/1b83fb72-2e19-11e6-83bd-adfad610f393.png)

**Comment by buddha87** [comment]
Can you check your developer console of your browser (Ctrl+Shitf+i in most browser). Perhaps there are any js errors and check if there is even a network request if you type more than 3 characters after the @ . Furthermore never delet a module without deinstalling it this leads to inconsitent data.

**Comment by rapidpage** [comment]
how may i do a full reinstall?

**Comment by rapidpage** [comment]
GET http://humhub.rapidpage.ca/assets/36303622/mail.css?v=1.1.0-beta.1 
index.php?r=admin%2Fsetting%2Fstatistic:1692 GET http://humhub.rapidpage.ca/assets/36303622/mail.js?v=1.1.0-beta.1 
index.php?r=admin%2Fsetting%2Fstatistic:1692 GET http://humhub.rapidpage.ca/assets/36303622/mail.js?v=1.1.0-beta.1 404 (Not Found)

**Comment by rapidpage** [comment]
GET http://humhub.rapidpage.ca/assets/36303622/mail.css?v=1.1.0-beta.1 
index.php?r=space%2Fspace&sguid=d05e865b-b9e4-454b-8ba3-10324f3fb11c:2623 GET http://humhub.rapidpage.ca/assets/36303622/mail.js?v=1.1.0-beta.1 
index.php?r=space%2Fspace&sguid=d05e865b-b9e4-454b-8ba3-10324f3fb11c:2623 GET http://humhub.rapidpage.ca/assets/36303622/mail.js?v=1.1.0-beta.1 404 (Not Found)
jquery.js?v=1465277179:9064 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by buddha87** [comment]
Please delete the content of the 'asset' directory in your humhub root, this should fix the 404 (Not Found) of the mail.js. Regarding your @ mentioning perhaps you have to rebuild your search index as described here: https://www.humhub.org/docs/guide-admin-adv-search.html

**Comment by rapidpage** [comment]
I am so appreciative of your tremendous support, both the @ function works and the mail module works too!
