### ISSUE TITLE
Oooops... It looks like you may have taken the wrong turn.

### ISSUE THREAD

**Issue by rapidpage** [humhub/humhub-modules-mail#98]
When I was using "breaking news" I get "Oooops... It looks like you may have taken the wrong turn." after hitting save!

**Comment by rapidpage** [comment]
here is the error message:
exception 'yii\base\ErrorException' with message 'Call to undefined method humhub\modules\user\models\Setting::findAll()' in /home/hhrpadmin/public_html/protected/modules/breakingnews/controllers/AdminController.php:35 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleFatalError() #1 {main}

**Comment by buddha87** [comment]
You are using v1.1 right ? Some modules are not compatible with this version yet.

**Comment by ananejoshua** [comment]
Oooops... It looks like you may have taken the wrong turn.
An internal server error occurred. how can i fix it
